"""Alter studentCourse fk columns

Revision ID: 6743845d9722
Revises: 90d7f3dd8e33
Create Date: 2023-02-19 23:07:26.421088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6743845d9722'
down_revision = '90d7f3dd8e33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentCourses', sa.Column('userId', sa.Integer(), nullable=True))
    op.add_column('studentCourses', sa.Column('courseId', sa.Integer(), nullable=True))
    op.drop_constraint('studentCourses_Course_fkey', 'studentCourses', type_='foreignkey')
    op.drop_constraint('studentCourses_User_fkey', 'studentCourses', type_='foreignkey')
    op.create_foreign_key(None, 'studentCourses', 'users', ['courseId'], ['id'])
    op.create_foreign_key(None, 'studentCourses', 'courses', ['userId'], ['id'])
    op.drop_column('studentCourses', 'User')
    op.drop_column('studentCourses', 'Course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentCourses', sa.Column('Course', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('studentCourses', sa.Column('User', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'studentCourses', type_='foreignkey')
    op.drop_constraint(None, 'studentCourses', type_='foreignkey')
    op.create_foreign_key('studentCourses_User_fkey', 'studentCourses', 'courses', ['User'], ['id'])
    op.create_foreign_key('studentCourses_Course_fkey', 'studentCourses', 'users', ['Course'], ['id'])
    op.drop_column('studentCourses', 'courseId')
    op.drop_column('studentCourses', 'userId')
    # ### end Alembic commands ###
