"""Refactor many to many

Revision ID: 90d7f3dd8e33
Revises: d4d53390ebed
Create Date: 2023-02-19 22:29:31.173154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d7f3dd8e33'
down_revision = 'd4d53390ebed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courseLikes_id', table_name='courseLikes')
    op.drop_column('courseLikes', 'isLiked')
    op.add_column('studentCourses', sa.Column('User', sa.Integer(), nullable=True))
    op.add_column('studentCourses', sa.Column('Course', sa.Integer(), nullable=True))
    op.drop_index('ix_studentCourses_id', table_name='studentCourses')
    op.drop_constraint('studentCourses_studentId_fkey', 'studentCourses', type_='foreignkey')
    op.drop_constraint('studentCourses_courseId_fkey', 'studentCourses', type_='foreignkey')
    op.create_foreign_key(None, 'studentCourses', 'users', ['Course'], ['id'])
    op.create_foreign_key(None, 'studentCourses', 'courses', ['User'], ['id'])
    op.drop_column('studentCourses', 'name')
    op.drop_column('studentCourses', 'courseId')
    op.drop_column('studentCourses', 'studentId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentCourses', sa.Column('studentId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('studentCourses', sa.Column('courseId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('studentCourses', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'studentCourses', type_='foreignkey')
    op.drop_constraint(None, 'studentCourses', type_='foreignkey')
    op.create_foreign_key('studentCourses_courseId_fkey', 'studentCourses', 'courses', ['courseId'], ['id'])
    op.create_foreign_key('studentCourses_studentId_fkey', 'studentCourses', 'users', ['studentId'], ['id'])
    op.create_index('ix_studentCourses_id', 'studentCourses', ['id'], unique=False)
    op.drop_column('studentCourses', 'Course')
    op.drop_column('studentCourses', 'User')
    op.add_column('courseLikes', sa.Column('isLiked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_courseLikes_id', 'courseLikes', ['id'], unique=False)
    # ### end Alembic commands ###
