"""Add new column to course like

Revision ID: d4d53390ebed
Revises: dae1fe9d0750
Create Date: 2023-02-19 12:26:25.698743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d4d53390ebed"
down_revision = "dae1fe9d0750"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courseLikes", sa.Column("isLiked", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courseLikes", "isLiked")
    # ### end Alembic commands ###
