"""First migration

Revision ID: dae1fe9d0750
Revises: 
Create Date: 2023-02-14 20:31:04.328603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dae1fe9d0750"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("firstName", sa.String(), nullable=True),
        sa.Column("lastName", sa.String(), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("teacher", "student", "staff", name="roleenum"),
            nullable=True,
        ),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("postalCode", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("teacherId", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["teacherId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_courses_id"), "courses", ["id"], unique=False)
    op.create_table(
        "phoneNumbers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=True),
        sa.Column("phoneNumber", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_phoneNumbers_id"), "phoneNumbers", ["id"], unique=False)
    op.create_table(
        "courseLikes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("courseId", sa.Integer(), nullable=True),
        sa.Column("studentId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["courseId"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["studentId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_courseLikes_id"), "courseLikes", ["id"], unique=False)
    op.create_table(
        "studentCourses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("courseId", sa.Integer(), nullable=True),
        sa.Column("studentId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["courseId"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["studentId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_studentCourses_id"), "studentCourses", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_studentCourses_id"), table_name="studentCourses")
    op.drop_table("studentCourses")
    op.drop_index(op.f("ix_courseLikes_id"), table_name="courseLikes")
    op.drop_table("courseLikes")
    op.drop_index(op.f("ix_phoneNumbers_id"), table_name="phoneNumbers")
    op.drop_table("phoneNumbers")
    op.drop_index(op.f("ix_courses_id"), table_name="courses")
    op.drop_table("courses")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
